Декоративные элементы на главной странице
htmlacademy-htmlcss/1814839-nerds-31 pull request #10
Opened 2021-07-13 15:06 UTC by lynx-boop

2021-07-13 15:36 UTC, wrgraff requested changes
Надо еще добавить активный пункт меню с подчеркиванием.

А карте заменить `min-width` и `min-height` на просто высоту и ширину. Всю магию остальную там делает object-fit (а то сейчас горизонтальная прокрутка вызывается)

2021-07-13 15:36 UTC, wrgraff commented on css/style.css
> +/* FIXME возможно, здесь нужно увеличить кликабельную область через паддинги для ссылки */
Возможно )

2021-07-13 15:36 UTC, wrgraff commented on css/style.css
> +}
Эээ, чтобы это ни было — в верстке его нет.
Вообще, маркер можно было бы прямо вместе с картинкой карты экспортировать.
 
Или в принципе пока его опустить

2021-07-13 15:36 UTC, wrgraff commented on css/style.css
> +    border: none;
Посмотри, у них есть еще отступы, при чем и внешние, и внутренние
Они сдвигают немного весь список чекбоксов

2021-07-13 15:36 UTC, wrgraff commented on css/style.css
> +    /* padding: добавить */
Так вот добавь же ))

2021-07-13 15:36 UTC, wrgraff commented on catalog.html
> +                                    от <input type="number" name="min-price" value="0">
Почему один текст, а другой номер?
Поставь оба текст, ведь и в первый инпут при некоторых параметрах могут попасть значения с разрывом.
Например "от 1 500"

2021-07-13 15:36 UTC, wrgraff commented on index.html
> +        </div>
Не нужен нам маркер этот, лучше картинку сделать сразу с ним

2021-07-14 09:18 UTC, lynx-boop commented on css/style.css
> +/* FIXME возможно, здесь нужно увеличить кликабельную область через паддинги для ссылки */
Увеличила)

2021-07-14 09:20 UTC, lynx-boop commented on css/style.css
> +}
Добила маркер)

2021-07-14 10:01 UTC, merged