Домашнее задание 2.19. Разметка главной страницы
htmlacademy-htmlcss/1814839-nerds-31 pull request #2
Opened 2021-05-22 19:01 UTC by lynx-boop

2021-05-23 16:04 UTC, wrgraff requested changes
Страницу каталога я пока не смотрел. Может ты по правкам у первой странице захочешь и там что-то поправить сразу.

Немного о том, как я ревью делаю.
Важные моменты, на которые нужно обязательно обратить внимание, я отмечаю смайлом ракеты `🚀`. То, что в правках не нуждается, отмечено смайлом `👍`. Некоторые комментарии без отметок. Если не понимаешь их или не успеваешь, то можно их оставить до следующей консультации или же вообще пропустить.
Еще прошу не нажимать на кнопку "Resolve conversation". Мне потом неудобно смотреть что я там написал. Пускай это будет моя кнопка =) Я буду ее жать если проблема исправлена. Ты можешь для себя тоже отмечать исправленный комментарий каким-то эмодзи, или писать комментарий в ответ. Как захочешь.

2021-05-24 15:39 UTC, lynx-boop commented on img/illustration-1 1.svg
> +<svg width="300" height="146" viewBox="0 0 300 146" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
+

2021-05-26 21:15 UTC, wrgraff requested changes
Отсыпал правок уже по обеим страницам =)

2021-05-26 21:15 UTC, wrgraff commented on catalog.html
> +                    <input type="text" name="price" value="15000">
Как это у инпутов одинаковые имена?
Они будут отправлять значение в одно и то же поле данных. Это подходит для взаимоисключающих элементов или объединяющихся (как чекбоксы).
А для текстовых инпутов это не подходит

2021-05-26 21:15 UTC, wrgraff commented on catalog.html
> +                    </legend>
Уоу! Откуда пятый уровень?
Заголовки должны ветвиться как дерево: заголовок более низкого уровня растет из заголовка на уровень выше

2021-05-26 21:15 UTC, wrgraff commented on catalog.html
> +                    <legend>
Вообще, ели есть легенда, то заголовок и не нужен уже.
Легенды для группы полей уже достаточно

2021-05-26 21:15 UTC, wrgraff commented on catalog.html
> +            <form method="get" action="#">
`action` должен вести на `https://echo.htmlacademy.ru`, чтобы работу формы можно было проверить

2021-05-26 21:15 UTC, wrgraff commented on catalog.html
> +                                <input type="radio" name="grid.system" value="adpt" checked>Адаптивная
Не пиши имя через точку, используем там только строчные буквы и дефисы.
Точки могут не обработаться

2021-05-26 21:15 UTC, wrgraff commented on catalog.html
> +            </form>
Направления по сути работают как и типы сортировки. Размечать тегами их нужно аналогично

2021-05-26 21:15 UTC, wrgraff commented on catalog.html
> +                        <h3>SEDONA</h3>
Внимательнее читаем [ТЗ](https://up.htmlacademy.ru/htmlcss/31/project/nerds#nerds-3-10)

2021-05-26 21:15 UTC, wrgraff commented on catalog.html
> +                            <!--<img src="">-->
Эта картинка — контентная. Ведь очень важно показать что за шаблон мы продаем. Это не просто какой-то декор

2021-05-26 21:15 UTC, wrgraff commented on catalog.html
> +                    <button type="button">9 900 ₽</button>
В интернет-магазинах принято делать такие кнопки с помощью ссылок.
Это критичный функционал для магазинов, поэтому в ссылку зашивают параметры, которые при переходе добавляют товар, а затем переадресовывают обратно.
Так даже при сломавшемся js добавление в корзину будет работать

2021-05-27 15:56 UTC, lynx-boop commented on catalog.html
> +    </header>
ОЙ

2021-05-27 16:00 UTC, lynx-boop commented on catalog.html
> +                    <input type="text" name="price" value="15000">
ОЙ копипастила невнимательно

2021-05-29 11:22 UTC, wrgraff commented on index.html
> +          <button type="button">Узнать больше</button>
Ты так и не ответила, что же должно произойти по нажатию на кнопку?

2021-05-29 11:22 UTC, wrgraff commented on index.html
> +          <button type="button">Заказать</button>
Аналогичный вопрос как у предыдущей кнопки )
Я еще не кидал [эту статью](https://tml.io/doiit)?

2021-05-29 11:22 UTC, wrgraff commented on index.html
> +      <button type="button">Напишите нам</button>
что-то не ладится у тебя с кнопками ))

2021-05-29 11:22 UTC, wrgraff commented on catalog.html
> +                    <a>Клиенты</a>
Похоже на текущую страницу.
Но мы же в каталоге

2021-05-29 11:22 UTC, wrgraff commented on catalog.html
> +                    <a href="#">Студия</a>
Студия 2 раза получилась

2021-05-29 11:22 UTC, wrgraff commented on catalog.html
> +                    <input type="text" name="price" value="15000">
Ну это ничего )

2021-05-29 12:17 UTC, wrgraff requested changes
Ну все, совсем немного правок.
Картинки будут простым заданием

2021-05-29 12:17 UTC, wrgraff commented on catalog.html
> +                    <a href="#">SEDONA
Можно добавить ссылку только на заголовок.
Ну и заголовок оставить, соответственно

2021-05-30 12:57 UTC, lynx-boop commented on index.html
> +          <button type="button">Узнать больше</button>
Скорее всего там вызывается какая-то другая страница, то есть по факту - это ссылка, а не кнопка. И возможно, что она ведет на каталог. Но с другой стороны - я не нашла в макете пруфов этого и подумала, что эта кнопка может вызывать модальное окно

2021-05-30 13:03 UTC, lynx-boop commented on index.html
> +          <button type="button">Заказать</button>
<img width="804" alt="Screenshot 2021-05-30 at 16 01 21" src="https://user-images.githubusercontent.com/84182995/120105142-60346600-c160-11eb-9401-b2fabe5b9adc.png">

Я ошиблась только в том, что обьявила ей тип, а не класс? Я не поняла(( Конпка "заказать" ведь добавляет макет в корзину, а значит, это кнопка, разве нет?

2021-05-30 17:09 UTC, wrgraff commented on index.html
> +          <button type="button">Заказать</button>
Да, правда, я зря это отметил как критичный комментарий.
Но на практике почти всегда это ссылки )

2021-05-30 17:10 UTC, wrgraff approved these changes

2021-05-30 17:10 UTC, merged