Графика всех страниц
htmlacademy-htmlcss/1814839-nerds-31 pull request #3
Opened 2021-05-30 18:52 UTC by lynx-boop

2021-05-31 15:33 UTC, wrgraff requested changes
Пару важных поправок я нашел )

2021-05-31 15:33 UTC, wrgraff commented on catalog.html
> +    <link rel="icon" href="img/Favicon/favicon152.svg" type="image/svg+xml">
Папки все должны быть строчными буквами, как и файлы.

В названиях файлов и папок нам нужно придерживаться нижнего регистра. Дело в том, что некоторые операционные системы учитывают регистр, а некоторые нет.
Может случиться так, что работали вы в системе, что регистр не учитывает, а проект опубликован в той, что учитывает. И тогда у вас все будет работать несмотря на разные буквы, а в опубликованной версии — нет. И это будет совсем не здорово.

Поэтому разработчики условились всегда называть файлы и папки в нижнем регистре.

2021-05-31 15:33 UTC, wrgraff commented on img/index/nerds_illustration.svg
> +<image id="image0" width="360" height="208" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAWgAAADQCAIAAAClaWwuAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyJpVFh0WE1MOmNvbS5hZG9iZ
Вот этот жуткий код говорит о том, что растровая картинка засунута в векторный файл.
А так не надо )

2021-05-31 15:33 UTC, wrgraff commented on index.html
> +        <img src="img/index/nerds_illustration.svg" width="360" height="208" alt="Абстракция и лого Нердс" />
Тут еще помимо формата вопрос: а контентная ли это картинка?

2021-05-31 15:33 UTC, wrgraff commented on index.html
> +              <img src="img/index/logo_borodinski.jpg" width="209" height="90" alt="Лого компании Borodinski">
А почему тут формат jpg вдруг в отличие от остальных логотипов?

2021-05-31 15:33 UTC, wrgraff commented on index.html
> +              <img src="img/index/logo_htmlacademy.png" width="199" height="57.16" alt="Лого компании HTML Academy">
Смотри, именно этот логотип (в отличие от других) выглядит вот так:
![изображение](https://user-images.githubusercontent.com/37917037/120215593-96481780-c23e-11eb-8158-271e838c6e8a.png)
О чем это говорит? =)

2021-05-31 15:53 UTC, lynx-boop commented on index.html
> +        <img src="img/index/nerds_illustration.svg" width="360" height="208" alt="Абстракция и лого Нердс" />
Мне показалось, что да - т.к. в этой секции рассказывается о дизайн-студии, но в пределах секции нигде ее названия, кроме картинки, больше нет. Поэтому я подумала, что это контентное изображение. Или я не права, и оно немного не так работает?)

2021-05-31 15:56 UTC, lynx-boop commented on index.html
> +              <img src="img/index/logo_borodinski.jpg" width="209" height="90" alt="Лого компании Borodinski">
Потому что он весил меньше, чем png, а в лекции рассказывали, что чем меньше весит изображение, тем лучше для сайта
<img width="534" alt="Screenshot 2021-05-31 at 18 55 27" src="https://user-images.githubusercontent.com/84182995/120218035-d6f56000-c241-11eb-853f-f6953133937f.png">

2021-05-31 15:59 UTC, lynx-boop commented on index.html
> +              <img src="img/index/logo_htmlacademy.png" width="199" height="57.16" alt="Лого компании HTML Academy">
ОЙ)

2021-05-31 16:02 UTC, wrgraff commented on index.html
> +              <img src="img/index/logo_borodinski.jpg" width="209" height="90" alt="Лого компании Borodinski">
Тут у меня есть 3 причины почему это не совсем так работает здесь =)

1. Справа у тебя картинка 2x судя по названию, то есть это картинка двойной плотности, получается. Она видимо вдвое больше по разрешению.
2. Если картинки обработать дополнительно инструментом для оптимизации, то такой тип картинки лучше сожмется в формате png, так как он оптимизирован под такие вот простые картинки.
3. Логотип довольно специфическая картинка: мы обычно не хотим, чтобы границы рисунка на нем размыливались. А png это формат сжатия без потери качества. Поэтому иногда даже с ущербом для веса выбирают png, чтобы сохранить картинку приятной для глаза

2021-05-31 16:03 UTC, wrgraff commented on index.html
> +        <img src="img/index/nerds_illustration.svg" width="360" height="208" alt="Абстракция и лого Нердс" />
Это ж и так сайт дизайн-студии, а секция озаглавлена "О нас" =)

2021-05-31 17:24 UTC, lynx-boop commented on index.html
> +        <img src="img/index/nerds_illustration.svg" width="360" height="208" alt="Абстракция и лого Нердс" />
Поняла)

2021-05-31 17:25 UTC, lynx-boop commented on index.html
> +              <img src="img/index/logo_borodinski.jpg" width="209" height="90" alt="Лого компании Borodinski">
Поняла, спасибо)

2021-05-31 18:04 UTC, wrgraff commented on index.html
> +              <img src="img/index/logo_htmlacademy.png" width="199" height="57.16" alt="Лого компании HTML Academy">
В атрибутах кстати только целые числа могут быть.
Не бывает у нас 16 сотых пикселя на мониторе )

2021-05-31 18:55 UTC, lynx-boop commented on index.html
> +              <img src="img/index/logo_htmlacademy.png" width="199" height="57.16" alt="Лого компании HTML Academy">
Поправила)

2021-05-31 20:27 UTC, wrgraff approved these changes
Сотые только не забудь убрать потом )

2021-05-31 20:27 UTC, wrgraff commented on index.html
> +              <img src="img/index/logo_htmlacademy.svg" width="199" height="57.16" alt="Лого компании HTML Academy">
А тут 16 сотых остались )

2021-05-31 20:27 UTC, merged

2021-06-01 07:31 UTC, lynx-boop commented on index.html
> +              <img src="img/index/logo_htmlacademy.svg" width="199" height="57.16" alt="Лого компании HTML Academy">
БЛИН!