Стидизация главной страницы
htmlacademy-htmlcss/1814839-nerds-31 pull request #4
Opened 2021-06-03 09:37 UTC by lynx-boop

2021-06-03 23:14 UTC, wrgraff requested changes

2021-06-03 23:14 UTC, wrgraff commented on css/style.css
> +    text-align: left;
Выравнивание текста то зачем?
Оно ж и так выравнивается по левому краю

2021-06-03 23:14 UTC, wrgraff commented on css/style.css
> +    /*Я не знаю, как нужно выравнивать этот блок - это же слайды...*/
Да пока норм, кроме фона тут пока ничего не нужно

2021-06-03 23:14 UTC, wrgraff commented on css/style.css
> +    /*это здесь на случай, если картинка не загрузится - лайв №4 55мин*/
Можно было и без указания минуты ))
Тут беда только в том, что картинка то имеет прозрачный фон. И серый будет видно

2021-06-03 23:14 UTC, wrgraff commented on css/style.css
> +/*туть будут свойства для кнопок слайдера .slider_button {}*/
Я бы рекомендовал стили для них перенести к слайдеру

2021-06-03 23:14 UTC, wrgraff commented on css/style.css
> +    color: rgba(255, 255, 255, .30);
Этот цвет (кстати, занеси его в переменную) можно вынести для всех кнопок в целом.

2021-06-03 23:14 UTC, wrgraff commented on css/style.css
> +}
Можно дать такие параметры всем кнопкам.
Кнопки по умолчанию будут красные. А уже другие цвета добавлять другими классами

2021-06-03 23:14 UTC, wrgraff commented on css/style.css
> +    color: white;
Цвет тоже можно в общий класс вынести, если сделать кнопку по умолчанию красной

2021-06-08 18:26 UTC, lynx-boop commented on index.html
> +<body class="page_body">
везде поправила)

2021-06-08 18:27 UTC, lynx-boop commented on index.html
> +      <ul class="site_navigation list">
Я присвоила его только затем, чтобы убрать из всех списков разом буллеты. Так делать не стоит? Переименовать класс во что-то более конкретное?

2021-06-08 18:32 UTC, lynx-boop commented on index.html
> +      <ul class="site_navigation list">
В учебном проекте рекомендовали сделать для корзины отдельный список, объясняя это тем, что на реальных проектах может встречаться такое, что заказчик просит добавить еще несколько пунктов, по смыслу подходящих этому списку (кнопку личного кабинета, например), - и к этому варианту развития событий нужно быть готовым) Или это лучше сделать как-то по-другому, и лишний список убрать?

2021-06-08 18:33 UTC, lynx-boop commented on css/style.css
> +    /*это здесь на случай, если картинка не загрузится - лайв №4 55мин*/
Это я для себя минуту указала - чтоб не забыть зачем я вообще добавила в код эту штуку) 
А насчет прозрачности - чет я не подумала... Исправлю)

2021-06-08 18:35 UTC, lynx-boop commented on css/style.css
> +/*туть будут свойства для кнопок слайдера .slider_button {}*/
Т.е. пока не научились делать слайдер, отложить работу над стилями для этих кнопок?

2021-06-08 18:58 UTC, lynx-boop commented on css/style.css
> +    color: rgba(255, 255, 255, .30);
Неожиданная поломка) 
Подскажи, плз, я когда назначила этот цвет всем кнопкам при active, к тем кнопкам, у которых был задан цвет текста для hover, это свойство не применилось. А к тем, у которых hover задан не был, сработали как надо и цвет текста при нажатии сменился на заданный. Это может быть связано с тем, что при нажатии на кнопку, на ней срабатывает и hover (потому что курсор навели), и active (потому что нажали), и к кнопке применяется тот стиль, который ниже по коду, т.е. hover?

2021-06-08 19:25 UTC, lynx-boop commented on index.html
> +      <h2 class="about_us" hidden>О нас</h2>
Да, секции))

2021-06-08 20:40 UTC, lynx-boop commented on catalog.html
> +
Так это во второй домашке будет) В этой то только главная страница. Но я все-равно добавлю

2021-06-08 20:43 UTC, lynx-boop commented on catalog.html
> +    <header class="main_header inner_page">
Подумала и поняла, что не нужен. Переборщила с классами)

2021-06-08 21:32 UTC, lynx-boop commented on css/style.css
> +    --active_yellow: #E5A722;
Интересная система. Немного непонятная, но в целом - удобно. Буду использовать, переименую цвета

2021-06-09 16:28 UTC, lynx-boop commented on css/style.css
> +    --active_yellow: #E5A722;
Разобралась) Действительно удобно!

2021-06-09 19:30 UTC, lynx-boop commented on css/style.css
> +    /*потом изменю на тот фон, который будет нужен, если будет нужен*/
Вообще не помню, зачем я его делала о__О

2021-06-09 19:31 UTC, lynx-boop commented on css/style.css
> +    /*потом изменю на тот фон, который будет нужен, если будет нужен*/
Я его делала, потому что в лекции говорили так сделать, и я подумала, что вот эта красная полосочка - это и есть фон. Но сейчас понимаю, что нет)

2021-06-09 22:24 UTC, wrgraff commented on catalog.html
> +
Но стили же подключила!
Если бы не подключила, я бы не сказал ничего =)

2021-06-09 22:24 UTC, wrgraff commented on index.html
> -  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
Обрати внимание на вот эту часть ссылок: `wght@400;500;700`

Первая ссылка подключает только базовый шрифт (у нее параметра этого нет): весом 400.
Вторая подключала 400 и 500.
Третья — 400, 500 и 700.

Тебе нужны все три. Вопрос: какую ссылку надо было оставить?

2021-06-09 22:24 UTC, wrgraff commented on index.html
> +      <ul class="site_navigation list">
Если это класс для удаления буллитов, то надо добавить ясности.
Вот я смотрю на класс `list` и не очень понимаю что он дает. Вижу, что он говорит мне "список". Но это и так список. Так зачем же класс? И мне придется лезть в стили, разбираться.

Надо назвать его конкретнее. Декларативнее.
`list-style-none`, например. Длинно, да, зато понятно за что отвечает этот утилитарный класс.

2021-06-09 22:40 UTC, wrgraff commented on index.html
> +      <ul class="site_navigation list">
Эээ...
Мысль интересная, конечно, но странноватая. И у меня на это пять причин (c):

1. Довольно странно фантазировать о том, что заказчик что-то там попросит добавить. А если не попросит? Так и будем со списком из одного пункта сидеть?
2. Что, если он попросит добавить, но дизайнер это нарисует так, что наш список все равно не к месту будет?
3. Допустим, нас попросят добавить еще один пункт. Будет 2 пункта. Этого достаточно для списка? У списков смысл в чем: узнать заранее сколько будет нас пунктов ждет. Я понимаю, если это главное меню, список товаров, список фильтров... Их может быть как 2, так и 22. А тут сколько ссылок нам заказчик напихает? Ну еще парочку от силы.
4. Зачем заранее придумывать список, если все равно переверстывать придется скорее всего? Нужно же добавить иконку, поставить отступы, прописать ссылку и классы... Неужели сложно будет если что и список добавить?
5. список — это набор однородных, схожих элементов. Я бы поставил под сомнение, что ссылки "войти" и "корзина" так уж схожи.

В общем, не знаю. Выглядит как преждевременная оптимизация.
Есть вещи, которые реально будут меняться часто в интерфейсе. Состав меню. Состав фильтров. Количество и порядок карточек товаров. Ссылки на номера страниц. Описание и состав услуг. Количество и содержание слайдов.
Но заранее продумывать как изменится состав самого интерфейса это что-то непонятное мне.

2021-06-09 22:42 UTC, wrgraff commented on index.html
> +      <h2 class="about_us" hidden>О нас</h2>
))

2021-06-09 22:55 UTC, wrgraff commented on index.html
> +      <ul class="about-us-list list">
У тебя получилось 2 списка `about-us-list`.
В самом по себе повторении классов нет ничего плохого, конечно, это полностью нормально.

Но стили то у нас для оформления нужны. А списки эти совсем не похожи )

2021-06-09 22:55 UTC, wrgraff commented on index.html
> +      <p class="friendship social">Скидка 10% для друзей из социальных сетей.</p>
Опять же, зачем тебе 2 одинаковых класса? Они совсем не похожи внешне.
И лучше искать суть элемента, в плане того, в какой роли он выступает в дизайне. Например, тут у нас внешне заголовок и текст.

Не заморачиваемся. Например, так:
```suggestion
      <p class="footer-title">Давайте дружить, это выгодно!</p>
      <p class="footer-text">Скидка 10% для друзей из социальных сетей.</p>
```

2021-06-09 22:55 UTC, wrgraff commented on css/style.css
> +    --active_yellow: #E5A722;
Да, может быть сперва немного непривычно, но в итоге она здорово упрощает жизнь. Особенно когда стилизовать детали начинаешь и цветов становится много.
Ну, а хороший дизайнер систему изначально продумывает, конечно. Но тогда можно смотреть что у дизайнера за система и использовать ее. Но многие сразу в дизайне используют эту (например, я :) )

2021-06-09 22:58 UTC, wrgraff commented on css/style.css
> +    --black-900: #000000;
Обычно у черного и белого оттенков не бывает )

2021-06-09 22:58 UTC, wrgraff commented on css/style.css
> +    /*потом изменю на тот фон, который будет нужен, если будет нужен*/
Там у них наверное в Барбершопе потому что цвет ссылки как раз меняется?
А у нас не так будет.

2021-06-09 23:00 UTC, wrgraff commented on css/style.css
> +    /*это здесь на случай, если картинка не загрузится - лайв №4 55мин*/
В любом случае будет видно что и как, такое не пропустим если что!

2021-06-09 23:02 UTC, wrgraff commented on css/style.css
> +/*туть будут свойства для кнопок слайдера .slider_button {}*/
Нет, в смысле стили для кнопок слайдера писать не в той части кода, где стили для кнопок, а в той, где стили для слайдера и слайдов =)
Это вообще только про место где писать стили. Не так существенно.

Кнопки полностью на лекции про декоративные элементы сделаем.

2021-06-09 23:09 UTC, wrgraff commented on css/style.css
> +    color: rgba(255, 255, 255, .30);
Да, конечно, именно так все и есть.
Поэтому, в рамках одного класса `active` должен идти после `hover`. Даже если они меняют разные свойства, все равно стоит взять это на вооружение как привычку.

2021-06-09 23:13 UTC, wrgraff requested changes
Теперь намноооооого меньше поправок.
Всего парочка важных )

2021-06-09 23:13 UTC, wrgraff commented on css/style.css
> +    background-color: var(--red-700);
Так смотри, и это можно сделать стилями `button`. Потому что все красные кнопки такие. И если у нас в базе кнопка красная, то для нее и прописать это.

А потом уже отдельно поменять эти стили для зеленой, желтой и серой кнопки (серая наверное в каталоге появится только)

2021-06-09 23:13 UTC, wrgraff commented on css/style.css
> +    background-color: var(--grey-310);
А. Я бы ее тоже как и остальные цветом окрестил

2021-06-10 05:09 UTC, lynx-boop commented on index.html
> -  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
Блин) Последнюю)

2021-06-10 16:17 UTC, wrgraff commented on index.html
> -  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
Точно ))

2021-06-10 16:17 UTC, wrgraff approved these changes

2021-06-10 16:17 UTC, merged