Сетка на гридах для главной страницы
htmlacademy-htmlcss/1814839-nerds-31 pull request #6
Opened 2021-06-29 13:55 UTC by lynx-boop

Signed-off-by: lynx-boop <shimukurumhi@gmail.com>

---
:mortar_board: [Сетка на гридах для главной страницы](https://up.htmlacademy.ru/htmlcss/31/user/1814839/tasks/7)

2021-06-29 23:37 UTC, wrgraff requested changes

2021-06-29 23:37 UTC, wrgraff commented on css/style.css
> +.center {
Обычно такой класс называют `container`. Де-факто это стандарт.
Но не обязательно

2021-06-29 23:37 UTC, wrgraff commented on css/style.css
> +    padding-left: 10px;
Очень странный отступ только с одной стороны, зачем он?

2021-06-29 23:37 UTC, wrgraff commented on css/style.css
> +    margin: 50px auto;
Можно написать отдельно верх и низ, тогда не придется менять левый и правый. То есть, сделать это так, чтобы не перебивать стили блока `.center`
```suggestion
    margin-top: 50px;
    margin-bottom: 50px;
```

2021-06-29 23:37 UTC, wrgraff commented on css/style.css
> +    margin: 0 10px;
Не совсем понятно в чем логика отступов, если в самой сетке есть `gap`, который и сам прекрасно должен отступы расставить

2021-06-29 23:37 UTC, wrgraff commented on css/style.css
> +    height: 182px;
Лучше не использовать высоту на контейнере, так как это блокирует возможности переполнения7
Вместо этого ты можешь ее использовать для элементов

2021-06-29 23:37 UTC, wrgraff commented on css/style.css
> +    grid-template-columns: 1fr;
А с какой целью тут одноколоночный грид?
Если его убрать, то ничего и не изменится

2021-06-29 23:37 UTC, wrgraff commented on css/style.css
> +    box-sizing: border-box;
Не нужно менять поведение расчета размера блоков для одного единственного элемента. Это неправильно: либо меняем всем, либо никому.
Я писал об этом [на канале большой пост](https://t.me/mentoriumChannel/59), там даже 2 сообщения

2021-06-29 23:37 UTC, wrgraff commented on css/style.css
> +}
Про то, как сделать классные контакты с переполнением у меня [есть отдельное видео](https://youtu.be/Ccmu3wrjY8o).

2021-06-29 23:37 UTC, wrgraff commented on css/style.css
> +    width: 1440px;
Карта должна тянуться во всю ширину экрана

2021-06-29 23:37 UTC, wrgraff commented on index.html
> +      <div class="main-navigation-wrapper center">
Обертка тут на самом деле не так уж нужна. Все свойства сетки вполне можно прописать и для самого `main-navigation`

2021-06-29 23:37 UTC, wrgraff commented on index.html
> +    <div class="main-background">
Див с названием "основной фон" — это странно. Фон не может быть частью разметки, в этом же нет смысла.
Ты лучше задай фон для секции `.features`, в ней заведи обычный див с центрированием `.center`. Он будет слайды центрировать.

2021-06-29 23:37 UTC, wrgraff commented on index.html
> +    <div class="center">
Лучше так не делать, а примиксовать (добавить вторым классом) к каждой из секций.
Всегда будет возможность добавить в середину секцию с фоном, тянущемся до краев

2021-06-29 23:37 UTC, wrgraff commented on index.html
> +          <h4 class="uppercase">С 2004 года точность во всем:</h4>
На всякий случай обращу внимание:
класс с именем `uppercase` должен отвечать только за регистр.
Ты так создаешь утилитарный класс, который выполняет одну небольшую точечную задачу. В нем не должно быть ни изменений размера шрифта, ни цвета, ни жирности

2021-06-30 05:34 UTC, lynx-boop commented on css/style.css
> +    justify-self: left;
Да, ошиблась просто с классом

2021-06-30 05:39 UTC, lynx-boop commented on css/style.css
> +    padding-left: 10px;
Чтобы если что-то пойдет со страницей не так, текст не уползал за ее пределы, и пользователь мог увидеть его целиком. Так в лекции говорили

2021-06-30 06:22 UTC, lynx-boop commented on css/style.css
> +    grid-template-columns: 1fr;
Наверное, я пробовала разные подходы к верстке футера и забыла убрать грид за ненадобностью

2021-06-30 08:29 UTC, lynx-boop commented on index.html
> +    <div class="center">
А как тогда мне гарантировать, что все элементы будут одной ширины? Я попробовала примиксовать, и все элементы разъехались.

2021-06-30 08:38 UTC, lynx-boop commented on index.html
> +    <div class="main-background">
я попробовала сделать так, получаются белые поля... В каком месте тогда правильно будет задать серый фон для этой зоны? 
<img width="1440" alt="Screenshot 2021-06-30 at 11 37 11" src="https://user-images.githubusercontent.com/84182995/123929636-ae26ce80-d997-11eb-8892-995bd7f74f9f.png">

2021-06-30 08:46 UTC, lynx-boop commented on css/style.css
> +    padding-left: 10px;
Я пока убрала, но не понимаю, какую проблему он вызывает

2021-06-30 08:49 UTC, lynx-boop commented on css/style.css
> +    height: 182px;
Перенесла высоту из контейнера в авто-строку. Правильно ли это?

2021-06-30 08:51 UTC, lynx-boop commented on css/style.css
> +}
Из-за отставания, я ещё не дошла до лайва с флексами. А в твоем видео они есть. Я попыталась привести код к виду, который ты рекомендуешь, и окончательно запуталась. Стоит ли мне сейчас трогать флексы, ведь домашка пока про гриды?

2021-06-30 21:38 UTC, wrgraff commented on css/style.css
> +    padding-left: 10px;
Я не очень понял.
- если пойдет что-то не так — что именно? Пойти не так может много всего, тут конкретика нужна.
- мне вообще сложно представить, что текст уползет за пределы страницы. В каком случае это может произойти?
- если текст будет уползать за страницу (хотя не очень понимаю что это), то как `padding` этому помешает? Будет уползать на 10 пикселей меньше?
- откуда там текст, это же логотип
- а как быть с тем, что этот отступ создаст лишний сдвиг логотипу?

В конце концов, отступ есть в самом `.container`.
Он делается, чтобы контент не прижимался при минимальной ширине к краям экрана. В блоке-контейнере его вполне достаточно будет.

2021-06-30 21:41 UTC, wrgraff commented on css/style.css
> +    height: 182px;
Да, тоже вариант

2021-06-30 21:41 UTC, wrgraff commented on css/style.css
> +    grid-template-columns: 1fr;
Бывает )

2021-06-30 21:46 UTC, wrgraff commented on css/style.css
> +}
Флекс там в основном немного аккуратности добавляет.
Главное, сделать логику. Сейчас у тебя карта просто за блоком контактов, а надо поставить ее под него. У них для этого должна быть общая обертка. К которой и привязывается карта.

2021-06-30 21:46 UTC, wrgraff commented on css/style.css
> +}
У тебя почти все сделано )
Флекс там не принципиален

2021-06-30 21:49 UTC, wrgraff commented on index.html
> +    <div class="main-background">
Тот способ, что я описал, не должен привести к такому виду.
Попробуй сделать это и отправить на проверку, я смогу тогда этот код посмотреть и увидеть что пошло не так.

Фон должен быть у `.features`, а контейнер — внутри

2021-06-30 21:54 UTC, wrgraff commented on index.html
> +    <div class="center">
Такого не может быть. Контейнер и предназначен для того чтобы элементы были одной ширины, так как в нем то ширина прописана.
Что он вокруг секций, что примиксован к каждой как второй класс (так `<section class="services container">`) — должен работать. Главное для самих секций отступы и ширину не трогать

2021-06-30 21:56 UTC, wrgraff commented
Просмотрел еще раз ревью, на вопросы ответил.
Если не получается что-то, то отправь не получившуюся версию, я посмотрю что именно там не так пошло.

2021-07-01 11:14 UTC, lynx-boop commented on css/style.css
> +    padding-left: 10px;
Поняла, спасибо!

2021-07-01 15:52 UTC, lynx-boop commented on css/style.css
> +}
ура ура все получилось ура

2021-07-01 16:02 UTC, lynx-boop commented on index.html
> +    <div class="center">
Все, я догадалась, где была ошибка :))

2021-07-01 23:33 UTC, wrgraff reviewed
Так, ну в принципе кроме блока со слайдером все ок.
По этому блоку [сделал видео на 3 минутки](https://youtu.be/FZvR-cRKpSo), где прямо в инспекторе браузера делаются поправки. Видео без звука, поэтому "следим за руками", как говорится )
Я там нахожу лишнюю обертку контейнером (в этом ошибка) и еще убираю лишнюю обертку в навигации: перемещаю сетку и контейнер на основной блок, ставлю внутренний отступ и фон даю элементу на уровень выше: хэдеру.

Но главное со слайдами разобраться.

П.С.: если смотришь ревью ночью, а не на следующий день, видео может быть в обработке или плохом качестве

2021-07-03 12:22 UTC, wrgraff approved these changes

2021-07-03 12:22 UTC, merged