Сетка на флексах для главной страницы
htmlacademy-htmlcss/1814839-nerds-31 pull request #8
Opened 2021-07-06 19:12 UTC by lynx-boop

2021-07-06 21:05 UTC, wrgraff requested changes
Так, ну пока просто маловато.
Пора бы скрыть неактивные слайды, Сделать кнопки слайдов можно круглыми.
Соцсети надо бы уже в футере сделать круглыми и выставить пол месту и размеру

2021-07-06 21:05 UTC, wrgraff commented on css/style.css
> +    max-width: 300px;
Это не очень хорошо работает.

Там видимо проблема в том, что справа отступ нужен еще, чтобы 3 колонки дожать.
Используй паддинг для контейнера лучше

2021-07-06 21:05 UTC, wrgraff commented on css/style.css
> +    justify-content: space-between;
Зачем спейс-битвин, если элементы то вплотную стоят?

2021-07-07 19:30 UTC, wrgraff requested changes
Можно еще кнопкам сделать отступы, чтобы они были похожи на себя и выглядели по макету

2021-07-07 19:30 UTC, wrgraff commented on css/style.css
> +    height: 217px;
Высоту не фиксируем, делаем размер за счет отступов.

_Видимо, в данном случае надо было на `padding` переключиться._

2021-07-07 19:30 UTC, wrgraff commented on css/style.css
> +    justify-content: center;
Ну вот это все надо переместить в ссылку.
Ссылка и есть этот кругляк, и ссылка должна реагировать на наведение.
А то тут странное:
![изображение](https://user-images.githubusercontent.com/37917037/124815792-5a584e80-df70-11eb-9f6d-83190cfa71f9.png)

2021-07-07 19:30 UTC, wrgraff commented on css/style.css
> +    height: 81px;
Не задавай высоту элементам, это плохо. В случае переполнения элемент не сможет вырасти вниз и сетка сломается

2021-07-07 19:30 UTC, wrgraff commented on css/style.css
> +    overflow: hidden;
А `overflow` зачем?

Это не так решается. Просто текст внутри кнопки надо обернуть в span и скрыть уже его. Как со скрытыми заголовками поступить

2021-07-07 19:30 UTC, wrgraff commented on index.html
> +          </div> -->
Под "скрыть слайды" я не это имел ввиду =D
Речь о верстке.

Тебе что нужно? У тебя 3 слайда, один показать надо, другие спрятать.
Как это сделать? Скрываем слайд по умолчанию. Затем активному добавляем класс. И ему включаем отображение через этот класс.
JS потом сможет класс перемещать и показывать разные слайды

2021-07-08 10:33 UTC, lynx-boop commented on css/style.css
> +    overflow: hidden;
А, я поняла. Я подсмотрела это решение с overflow на стаке, потому что не знала, как убрать текст с кнопок, чтобы сделать их кругленькими

2021-07-08 14:39 UTC, lynx-boop commented on index.html
> +          </div> -->
Не поняла, как сделать :( Добавила в код два варианта, подскажи, плз, что я сделала там неправильно и как это исправить?

2021-07-08 16:04 UTC, wrgraff commented on css/style.css
> +    overflow: hidden;
А вот все проще )

2021-07-08 16:29 UTC, wrgraff requested changes
Слайдер добить бы надо

2021-07-08 16:29 UTC, wrgraff commented on css/style.css
> +    min-height: max-content;
Я не понимаю как это работает, а ты? ))

2021-07-08 16:29 UTC, wrgraff commented on css/style.css
> +показывался первый слайд, на вторую - второй и т.д. */
Так ведь никто и не говорил, что надо так делать.
Это делает js. Тебе только стили надо под него сделать

2021-07-08 16:29 UTC, wrgraff commented on css/style.css
> +показывался первый слайд, на вторую - второй и т.д. */
[Вот тут пояснительный ролик](https://www.dropbox.com/s/fgwhezzbygfs61j/%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D1%8C%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202021-07-08%20%D0%B2%2019.15.44.mov?dl=0).
Он там максимум в качестве 720, я его туда загрузил поскольку это проще и быстрее. Если скачать оригинал, он покачественнее будет

2021-07-08 18:12 UTC, lynx-boop commented on css/style.css
> +    min-height: max-content;
Что-то меня, видимо, переклинило. Оно ни на что не влияет

2021-07-08 23:31 UTC, lynx-boop commented on css/style.css
> +показывался первый слайд, на вторую - второй и т.д. */
Сделала по видео все, как ты показал, спасибо тебе огромное! Многое стало ясно)
Одно непонятно - я вроде все сделала по инструкции, но при активной кнопке цветной кружок внутри кнопки почему-то не кружок вовсе, а какой-то овал... Не понимаю, что и где я сделала не так

2021-07-08 23:38 UTC, wrgraff commented on css/style.css
> +показывался первый слайд, на вторую - второй и т.д. */
А у меня кружок )
Ну давай оставим это до декора если что

2021-07-08 23:38 UTC, wrgraff approved these changes

2021-07-08 23:38 UTC, merged